apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.clair.ports.api }}
    protocol: TCP
    name: api
  - port: {{ .Values.clair.ports.health }}
    protocol: TCP
    name: health
  selector:
    app: clair