apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  ports:
  - port: {{ .Values.postgres.service.port }}
    protocol: TCP
    name: http
  selector:
    app: postgres