apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
type: Opaque
data:
  postgres-password:  {{ .Values.postgres.password | b64enc | quote }}